const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANE_LANGUAGE:'CHANE_LANGUAGE',

    

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    USER_LOGIN_FAIL:'USER_LOGIN_FAIL',

    //admin
    FETCH_GENDER_START:'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIDED :'FETCH_GENDER_FAIDED',

    FETCH_POSITION_FAIDED :'FETCH_POSITION_FAIDED',
    FETCH_POSITION_SUCCESS:'FETCH_POSITION_SUCCESS',

    FETCH_ROLE_SUCCESS:'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIDED:'FETCH_ROLE_FAIDED',

    CREATE_USER_SUCCESS :'CREATE_USER_SUCCESS',
    CREATE_USER_FAILDED :'CREATE_USER_FAILDED',

    EDIT_USER_SUCCESS :'EDIT_USER_SUCCESS',
    EDIT_USER_FAILDED :'EDIT_USER_FAILDED',

    DELETE_USER_SUCCESS:'DELETE_USER_SUCCESS',
    DETELE_USER_FAILDED:'DETELE_USER_FAILDED',

    FETCH_ALL_USERS_SUCCESS:'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILDED:'FETCH_ALL_USERS_FAILDED',

    FETCH_ALL_DOCTORS_SUCCESS:'FETCH_ALL_DOCTORS_SUCCESS',
    FETCH_ALL_DOCTORS_FAILDED:'FETCH_ALL_DOCTORS_FAILDED',

    FETCH_TOP_DOCTORS_SUCCESS:'FETCH_TOP_DOCTORS_SUCCESS',
    FETCH_TOP_DOCTORS_FAILDED:'FETCH_TOP_DOCTORS_FAILDED',

    SAVE_DETAIL_DOCTORS_SUCCESS:'SAVE_DETAIL_DOCTORS_SUCCESS',
    SAVE_DETAIL_DOCTORS_FAILDED:'SAVE_DETAIL_DOCTORS_FAILDED',

})

export default actionTypes